/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package progressivebooker;

/**
 *
 * @author Marcin
 */
public class ProgressiveBooker extends javax.swing.JPanel {

    private ProgressiveSimulator ps;
            
    public ProgressiveBooker() {
        initComponents();
        
        ps = new ProgressiveSimulator();
        int df = jSliderDrawFrequency.getValue();
        jLabelDrawFrequency.setText(Integer.toString(df));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelProgressiveBooker = new javax.swing.JPanel();
        jTextFieldEventsNumber = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaSimulation = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaOdds = new javax.swing.JTextArea();
        jButtonGenerate = new javax.swing.JButton();
        jLabelDrawFrequency = new javax.swing.JLabel();
        jSliderDrawFrequency = new javax.swing.JSlider();
        jButtonSimulate = new javax.swing.JButton();

        jTextFieldEventsNumber.setText("number");

        jTextAreaSimulation.setColumns(20);
        jTextAreaSimulation.setRows(5);
        jScrollPane2.setViewportView(jTextAreaSimulation);

        jTextAreaOdds.setColumns(20);
        jTextAreaOdds.setRows(5);
        jScrollPane1.setViewportView(jTextAreaOdds);

        jButtonGenerate.setText("Generate");
        jButtonGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerateActionPerformed(evt);
            }
        });

        jLabelDrawFrequency.setText("jLabel1");

        jSliderDrawFrequency.setMaximum(35);
        jSliderDrawFrequency.setMinimum(20);
        jSliderDrawFrequency.setValue(20);
        jSliderDrawFrequency.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderDrawFrequencyStateChanged(evt);
            }
        });

        jButtonSimulate.setText("Simulate");
        jButtonSimulate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimulateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelProgressiveBookerLayout = new javax.swing.GroupLayout(jPanelProgressiveBooker);
        jPanelProgressiveBooker.setLayout(jPanelProgressiveBookerLayout);
        jPanelProgressiveBookerLayout.setHorizontalGroup(
            jPanelProgressiveBookerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jPanelProgressiveBookerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelProgressiveBookerLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanelProgressiveBookerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanelProgressiveBookerLayout.createSequentialGroup()
                            .addGroup(jPanelProgressiveBookerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelProgressiveBookerLayout.createSequentialGroup()
                                    .addComponent(jButtonGenerate)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldEventsNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelProgressiveBookerLayout.createSequentialGroup()
                                    .addComponent(jButtonSimulate)
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabelDrawFrequency)))
                            .addGap(23, 23, 23))
                        .addGroup(jPanelProgressiveBookerLayout.createSequentialGroup()
                            .addComponent(jSliderDrawFrequency, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(jPanelProgressiveBookerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        jPanelProgressiveBookerLayout.setVerticalGroup(
            jPanelProgressiveBookerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
            .addGroup(jPanelProgressiveBookerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelProgressiveBookerLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanelProgressiveBookerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelProgressiveBookerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonGenerate)
                            .addComponent(jTextFieldEventsNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanelProgressiveBookerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelProgressiveBookerLayout.createSequentialGroup()
                            .addGroup(jPanelProgressiveBookerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonSimulate)
                                .addComponent(jLabelDrawFrequency))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jSliderDrawFrequency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelProgressiveBooker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addComponent(jPanelProgressiveBooker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerateActionPerformed

        String eventsNumberString = jTextFieldEventsNumber.getText();
        int eventsNumber = Integer.parseInt(eventsNumberString);
        ps.generateOddsList(eventsNumber);
        String odds = ps.viewOdds();

        jTextAreaOdds.setText(odds);
    }//GEN-LAST:event_jButtonGenerateActionPerformed

    private void jSliderDrawFrequencyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderDrawFrequencyStateChanged

        int currentValue = jSliderDrawFrequency.getValue();
        jLabelDrawFrequency.setText(Integer.toString(currentValue));
    }//GEN-LAST:event_jSliderDrawFrequencyStateChanged

    private void jButtonSimulateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimulateActionPerformed

        int drawFrequency = jSliderDrawFrequency.getValue();
        String simulationInfo = ps.getPbm().simulate(drawFrequency, 10.0, ProgressionTypeENUM.Fibonacci);

        jTextAreaSimulation.setText(simulationInfo);
    }//GEN-LAST:event_jButtonSimulateActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGenerate;
    private javax.swing.JButton jButtonSimulate;
    private javax.swing.JLabel jLabelDrawFrequency;
    private javax.swing.JPanel jPanelProgressiveBooker;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSliderDrawFrequency;
    private javax.swing.JTextArea jTextAreaOdds;
    private javax.swing.JTextArea jTextAreaSimulation;
    private javax.swing.JTextField jTextFieldEventsNumber;
    // End of variables declaration//GEN-END:variables
}
