/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dataBase;

import javax.swing.JTextArea;

/**
 *
 * @author Marcin
 */
public class UpdateBet extends javax.swing.JFrame {

    /**
     * Creates new form UpdateBet
     */
    private int status = 1;     //jeszcze nierozstrzygnięty
    
    public UpdateBet() {
        initComponents();
        setFields();
    }
    
    private void setFields()
    {
        jRadioButtonWon.setText("Won");
        jRadioButtonLost.setText("Lost");
        jRadioButtonCanceled.setText("Canceled/Postponed");
        jRadioButtonUnresolved.setText("Unresolved");
        jButtonUpdateResult.setText("Confirm");
    }
    
    public void updateBet(QueryManager queryManager, int id)
    {
        queryManager.changeBetStatus(status, id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupResult = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaInfo = new javax.swing.JTextArea();
        jRadioButtonWon = new javax.swing.JRadioButton();
        jRadioButtonLost = new javax.swing.JRadioButton();
        jRadioButtonCanceled = new javax.swing.JRadioButton();
        jButtonUpdateResult = new javax.swing.JButton();
        jRadioButtonUnresolved = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextAreaInfo.setColumns(20);
        jTextAreaInfo.setRows(5);
        jScrollPane1.setViewportView(jTextAreaInfo);

        buttonGroupResult.add(jRadioButtonWon);
        jRadioButtonWon.setText("jRadioButton1");
        jRadioButtonWon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonWonActionPerformed(evt);
            }
        });

        buttonGroupResult.add(jRadioButtonLost);
        jRadioButtonLost.setText("jRadioButton2");

        buttonGroupResult.add(jRadioButtonCanceled);
        jRadioButtonCanceled.setText("jRadioButton3");

        jButtonUpdateResult.setText("jButton1");
        jButtonUpdateResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateResultActionPerformed(evt);
            }
        });

        buttonGroupResult.add(jRadioButtonUnresolved);
        jRadioButtonUnresolved.setSelected(true);
        jRadioButtonUnresolved.setText("jRadioButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonWon)
                            .addComponent(jRadioButtonLost)
                            .addComponent(jRadioButtonCanceled)
                            .addComponent(jRadioButtonUnresolved))
                        .addGap(0, 54, Short.MAX_VALUE))
                    .addComponent(jButtonUpdateResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButtonWon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonLost)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonCanceled)
                        .addGap(2, 2, 2)
                        .addComponent(jRadioButtonUnresolved)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonUpdateResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonWonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonWonActionPerformed
        
        if(jRadioButtonUnresolved.isSelected())
            status = 1;
        
        if(jRadioButtonWon.isSelected())
            status = 2;
        
        if(jRadioButtonLost.isSelected())
            status = 3;
        
        if(jRadioButtonCanceled.isSelected())
            status = 4;
        
        System.out.println(status);
    }//GEN-LAST:event_jRadioButtonWonActionPerformed

    private void jButtonUpdateResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUpdateResultActionPerformed

    public JTextArea getjTextAreaInfo()
    {
        return jTextAreaInfo;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateBet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateBet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateBet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateBet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateBet().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupResult;
    private javax.swing.JButton jButtonUpdateResult;
    private javax.swing.JRadioButton jRadioButtonCanceled;
    private javax.swing.JRadioButton jRadioButtonLost;
    private javax.swing.JRadioButton jRadioButtonUnresolved;
    private javax.swing.JRadioButton jRadioButtonWon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaInfo;
    // End of variables declaration//GEN-END:variables
}
